"""catalog.py — Fetches and caches Bedrock model catalog pages as Markdown files."""

import os
import re
import time
from datetime import datetime

from jinja2 import Template

import listing as lst
from boto3_helpers.bedrock import control as _bedrock_ctl

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CATALOG_DIR = os.path.join(os.path.dirname(__file__), "catalog")
_MAX_AGE_SECONDS = 86_400  # 1 day


# ---------------------------------------------------------------------------
# Jinja2 Markdown template
# ---------------------------------------------------------------------------

_CATALOG_TEMPLATE = """\
# {{ name }}

> *Catalog entry for Amazon Bedrock foundation model.*
> *Generated: {{ generated_at }}*
> *Cached for up to 24 hours. Delete this file to force a refresh.*

---

## Overview

| Field | Value |
|:------|:------|
| **Model Name** | {{ name }} |
| **Model ID** | `{{ model_id }}` |
| **Provider** | {{ provider }} |
| **Lifecycle Status** | {{ lifecycle_status }} |
| **Model ARN** | `{{ model_arn }}` |

---

## Capabilities

| Field | Value |
|:------|:------|
| **Input Modalities** | {{ input_modalities }} |
| **Output Modalities** | {{ output_modalities }} |
| **Inference Types Supported** | {{ inference_types }} |
| **Response Streaming** | {{ streaming }} |

---

## Customization

| Field | Value |
|:------|:------|
| **Customizations Supported** | {{ customizations }} |

---

## Pricing *(from local price table)*

| Metric | Price |
|:-------|------:|
| Input (per 1,000 tokens) | ${{ "%.6f" % in_price }} |
| Output (per 1,000 tokens) | ${{ "%.6f" % out_price }} |
{% if in_price == 0.0 and out_price == 0.0 %}
> *Pricing not available in local table for this model. Check the*
> *[AWS Bedrock Pricing page](https://aws.amazon.com/bedrock/pricing/) for up-to-date rates.*
{% endif %}

---

*Source: [AWS Bedrock `GetFoundationModel` API](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_GetFoundationModel.html)*
*Generated by Bedrock Model Compare on {{ generated_at }}*
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_filename(model_id: str) -> str:
    """Convert a model ID to a safe filename (replaces / : . with _)."""
    return re.sub(r"[^a-zA-Z0-9\-]", "_", model_id) + ".md"


def _is_fresh(filepath: str) -> bool:
    """Return True if the file exists and was modified within the last day."""
    try:
        age = time.time() - os.path.getmtime(filepath)
        return age < _MAX_AGE_SECONDS
    except OSError:
        return False


def _fetch_details(model_id: str) -> dict:
    """Call Bedrock GetFoundationModel and return the modelDetails dict."""
    return _bedrock_ctl.get_foundation_model(model_id)


def _render(details: dict, in_price: float, out_price: float) -> str:
    lifecycle = details.get("modelLifecycle", {})
    if isinstance(lifecycle, dict):
        lifecycle_status = lifecycle.get("status", "—")
    else:
        lifecycle_status = "—"

    return Template(_CATALOG_TEMPLATE).render(
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        name=details.get("modelName", "—"),
        model_id=details.get("modelId", "—"),
        provider=details.get("providerName", "—"),
        model_arn=details.get("modelArn", "—"),
        lifecycle_status=lifecycle_status,
        input_modalities=", ".join(details.get("inputModalities", [])) or "—",
        output_modalities=", ".join(details.get("outputModalities", [])) or "—",
        inference_types=", ".join(details.get("inferenceTypesSupported", [])) or "—",
        streaming="Yes" if details.get("responseStreamingSupported") else "No",
        customizations=", ".join(details.get("customizationsSupported", [])) or "None",
        in_price=in_price,
        out_price=out_price,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_or_create_catalog(model: dict) -> tuple[str, bool]:
    """
    Return (filepath, was_cached) for the model's catalog Markdown file.

    If a fresh file exists (<1 day old), it is reused and was_cached=True.
    Otherwise the Bedrock API is called, a new file is written, was_cached=False.
    """
    os.makedirs(CATALOG_DIR, exist_ok=True)

    model_id = model["modelId"]
    filename = _safe_filename(model_id)
    filepath = os.path.join(CATALOG_DIR, filename)

    if _is_fresh(filepath):
        return filepath, True

    details = _fetch_details(model_id)
    in_price, out_price = lst.get_pricing(model_id)
    content = _render(details, in_price, out_price)

    with open(filepath, "w", encoding="utf-8") as fh:
        fh.write(content)

    return filepath, False
