"""output.py — Renders model comparison results as a Markdown file via Jinja2."""

import os
from datetime import datetime

from jinja2 import Template

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "results")

# ---------------------------------------------------------------------------
# Jinja2 Markdown template
# ---------------------------------------------------------------------------
_MD_TEMPLATE = """\
# Bedrock Model Comparison

**Date**: {{ date }}
**Inference type**: {{ inference_type }}
**Prompt**: {{ prompt | replace('"', '\\"') }}
**Models compared**: {{ results | length }}

---

## Run Totals

{% set ok = results | selectattr('error', 'none') | list %}
| Metric | Value |
|:-------|------:|
| Successful models | {{ ok | length }} / {{ results | length }} |
| Total input tokens | {{ ok | sum(attribute='input_tokens') }} |
| Total output tokens | {{ ok | sum(attribute='output_tokens') }} |
| Total cost | **${{ "%.8f" % (ok | sum(attribute='total_cost')) }}** |

---

## Summary

*Sorted by total estimated cost (cheapest → most expensive). Failed models are at the bottom.*

{% set successful = results | selectattr('error', 'none') | list %}
{% set failed = results | selectattr('error') | list %}
{% if successful %}
| Rank | Model | Provider | Size | In tokens | Out tokens | Latency | In $/1k | Out $/1k | Total cost |
|-----:|-------|----------|:----:|----------:|-----------:|--------:|--------:|---------:|----------:|
{% for r in successful | sort(attribute='total_cost') -%}
| {{ loop.index }} | **{{ r.model_name }}** | {{ r.provider }} | {{ r.size }} | {{ r.input_tokens }} | {{ r.output_tokens }} | {{ "%.2f" % r.latency }}s | ${{ "%.6f" % r.in_price_per_k }} | ${{ "%.6f" % r.out_price_per_k }} | ${{ "%.8f" % r.total_cost }} |
{% endfor -%}
{% for r in failed -%}
| — | ~~{{ r.model_name }}~~ | {{ r.provider }} | {{ r.size }} | — | — | — | — | — | **ERROR** |
{% endfor %}
{% else %}
> **All models failed.** See Detailed Responses below for error messages.
{% endif %}

---

## Detailed Responses
{% for r in results | sort(attribute='total_cost') %}
### {{ loop.index }}. {{ r.model_name }}

{% if r.error %}
> **Error**: `{{ r.error }}`
{% else %}
| Field          | Value |
|:---------------|:------|
| Model ID       | `{{ r.model_id }}` |
| Provider       | {{ r.provider }} |
| Size           | {{ r.size }} |
| Input tokens   | {{ r.input_tokens }} |
| Output tokens  | {{ r.output_tokens }} |
| Latency        | {{ "%.2f" % r.latency }}s |
| Input cost     | ${{ "%.8f" % r.input_cost }} (@ ${{ "%.6f" % r.in_price_per_k }}/1k) |
| Output cost    | ${{ "%.8f" % r.output_cost }} (@ ${{ "%.6f" % r.out_price_per_k }}/1k) |
| **Total cost** | **${{ "%.8f" % r.total_cost }}** |

**Response:**

{{ r.output }}
{% endif %}
---
{% endfor %}

*Generated by [Bedrock Model Compare](../main.py) on {{ date }}*
"""


def render_comparison(prompt: str, results: list[dict], inference_type: str = "TEXT") -> str:
    """Render the Jinja2 template to a Markdown string."""
    return Template(_MD_TEMPLATE).render(
        date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        inference_type=inference_type,
        prompt=prompt,
        results=results,
    )


def save_results(prompt: str, results: list[dict], inference_type: str = "TEXT") -> str:
    """
    Render and save the comparison to results/comparison_YYYYMMDD_HHMMSS.md.

    Returns the absolute path to the written file.
    """
    os.makedirs(RESULTS_DIR, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename  = f"comparison_{timestamp}.md"
    filepath  = os.path.join(RESULTS_DIR, filename)

    content = render_comparison(prompt, results, inference_type)
    with open(filepath, "w", encoding="utf-8") as fh:
        fh.write(content)

    return filepath
